import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
// import "chartjs-plugin-datalabels";
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
  Tooltip,
  Legend,
} from "chart.js";
import { Bar } from "react-chartjs-2";
import React, { useState, useEffect, use } from "react";

ChartJS.register(
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
  Tooltip,
  Legend
);

const inter = Inter({ subsets: ["latin"] });

const data = {
  labels: [
    "L2ContrastReductionAttack",
    "VirtualAdversarialAttack",
    "L2FastGradientAttack",
    "L2BasicIterativeAttack",
  ],
  datasets: [
    {
      label: "Original Model Accuracy",
      fillColor: "green",
      data: [0.75, 0.75, 0.75, 0.75],
      borderColor: "rgb(0, 255, 0)",
      backgroundColor: "rgba(35, 158, 45, 0.8)",
    },
    {
      label: "Accuracy After FoolBox Attacks",
      fillColor: "red",
      data: [0.54, 0.47, 0.64, 0.34],
      borderColor: "rgb(53, 162, 235)",
      backgroundColor: "rgba(255, 0, 0, 0.8)",
    },
  ],
};

const options = {
  osition: "right",
  responsive: true,
  maintainAspectRatio: false,
  plugins: {
    legend: {
      position: "top",
    },
    title: {
      display: true,
      text: "Foolbox Attack Strength",
    },
  },
  scales: {
    y: {
      min: 0,
      max: 1,
    },
  },
};

const data2 = {
  labels: [
    "Fast Gradient Method",
    "Basic Iterative Method",
    "Madry et al",
    "Momentum Iterative Method",
  ],
  datasets: [
    {
      label: "Original Model Accuracy",
      data: [0.75, 0.75, 0.75, 0.75],
      borderColor: "rgb(0, 255, 0)",
      backgroundColor: "rgba(35, 158, 45, 0.8)",
    },
    {
      label: "Accuracy After Cleverhans Attacks",
      fillColor: "red",
      data: [0.32, 0.55, 0.7, 0.29],
      borderColor: "rgb(53, 162, 235)",
      backgroundColor: "rgba(255, 0, 0, 0.8)",
    },
  ],
};

const options2 = {
  osition: "right",
  responsive: true,
  maintainAspectRatio: false,
  plugins: {
    legend: {
      position: "top",
    },
    title: {
      display: true,
      //position: "center",
      text: "Cleverhans Attack Strength",
    },
  },
  scales: {
    y: {
      min: 0,
      max: 1,
    },
  },
};

const data3 = {
  labels: [
    "Original Model",
    "Basic Iterative Method",
    "Madry et al",
    "Momentum Iterative Method",
  ],
  datasets: [
    {
      label: "Original Model Accuracy",
      data: [0.75],
      borderColor: "rgb(0, 255, 0)",
      backgroundColor: "rgba(35, 158, 45, 0.8)",
    },
    {
      label: "Accuracy After Cleverhans Attacks",
      fillColor: "red",
      data: [0, 0.55, 0.7, 0.29],
      borderColor: "rgb(53, 162, 235)",
      backgroundColor: "rgba(255, 0, 0, 0.8)",
    },
  ],
};

const options3 = {
  osition: "right",
  responsive: true,
  maintainAspectRatio: false,
  plugins: {
    legend: {
      position: "top",
    },
    title: {
      display: true,
      //position: "center",
      text: "Cleverhans Attack Strength",
    },
  },
  scales: {
    y: {
      min: 0,
      max: 1,
    },
  },
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>Sample Charts</div>
        <div className={styles.Chart}>
          <Bar
            data={data}
            options={options}
            position="left"
            height="300px"
            width="300px"
          />
        </div>
        <div className={styles.Chart2}>
          <Bar
            data={data2}
            options={options2}
            position="left"
            height="300px"
            width="300px"
          />
        </div>
        <div className={styles.Chart3}>
          <Bar
            data={data3}
            options={options3}
            position="left"
            height="300px"
            width="300px"
          />
        </div>
        <div className={styles.grid}></div>
      </main>
    </>
  );
}
